### ISSUE TITLE
Fail to detect Hibernate upgrade

### ISSUE THREAD

**Issue by snicoll** [spring-io/bomr#2]
For some reason, bomr is unable to see that a new Hibernate version is available. This should be reproduced by checking out `4e92d590ad4` from the Spring Boot project and running an update.

With `4e92d590ad4` `hibernate.version` is at `5.3.3.Final` and `5.3.5.Final` is available.

**Comment by wilkinsona** [comment]
Interesting. It works now, but 5.3.6.Final has been released:

```
Hibernate 5.3.3.Final

    1. 5.3.4.Final
    2. 5.3.5.Final
    3. 5.3.6.Final

Please select a version:
```

I suspect that the `maven-metadata.xml` file wasn't updated properly when 5.3.4.Final and 5.3.5.Final were deployed but that's been corrected with 5.3.6.Final.

We could scrape the directory listing rather than parsing `maven-metadata.xml`, but I'm not sure that it's worth it. Thoughts?

**Comment by snicoll** [comment]
I am not sure it's worth it either.

**Comment by wilkinsona** [comment]
Ok. I'll close this for now. If it happens again, we can consider the scraping option.
